# Generated by Django 4.2.1 on 2023-06-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
    ]
